### ISSUE TITLE
Be more specific on connections

### ISSUE THREAD

**Issue by Rimbaldo** [SteveAmor/GPD2846#1]
Hi! Could you be more especific on wiring the digital ports to the pads? Each one of the three buttons has two pads. To which pads should each digital pin be connecte? To the more close to the edge of the pcb (to the right) or to the pads closer to the resistors?

If the connection should be made to the pads closer to the  resistors, should the pads closer to the edge of the board all be wired in series to 3.3V? Or it’s not needed? Thanks!

**Comment by SteveAmor** [comment]
The Arduino pins should connect to the pads closer to the resistors.  There is no need to connect 3.3V to the pins closer to the edge of the board.
